version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis_server
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
