services:
  db:
    restart: unless-stopped
    image: postgres:latest
    env_file:
      - prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432

  redis:
    restart: unless-stopped
    image: redis:latest
    env_file:
      - prod.env
    ports:
      - 6379:6379

  api:
    build:
      context: .
      target: production
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    env_file:
      - prod.env

volumes:
  postgres_data: