services:
  db:
    container_name: hackthelab-db
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432

  redis:
    container_name: hackthelab-redis
    restart: unless-stopped
    image: redis:latest
    environment:
      - REDIS_PASS
    command: ["redis-server", '--requirepass "$REDIS_PASS"']
    ports:
      - 6379:6379

  api:
    container_name: hackthelab-api
    restart: unless-stopped
    image: ghcr.io/michiganlabs/hack-the-lab-backend:latest
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_PASS
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data: