services:
  db:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - 5432:5432

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - 6379:6379

  api:
    build:
      context: .
      target: production
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASS=${REDIS_PASS}
    depends_on:
      - db
      - redis

volumes:
  postgres_data: