name: "Deploy Docker container to self-managed Runner"

on:
    push:
    # workflow_dispatch

jobs:
    run_container:
        name: Pull Docker image
        runs-on: 
            labels: [ "self-hosted", "Linux" ]

        env:
            TAG: "ghcr.io/michiganlabs/hack-the-lab-backend:latest"
        
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Pull docker image
              run: docker pull $TAG

            - name: stop any existing containers
              run: docker compose down

            - name: execute container
              run: docker compose up -d