name: "Deploy Docker"

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  run_container:
    runs-on: 
      labels: [ "self-hosted", "Linux" ]

    env:
      TAG: "ghcr.io/michiganlabs/hack-the-lab-backend:latest"
    
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Pull docker image
        run: docker pull $TAG

      - name: Create environment file
        run: |
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> prod.env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> prod.env
          echo POSTGRES_PASS=${{ secrets.POSTGRES_PASS }} >> prod.env
          echo REDIS_USER=${{ secrets.REDIS_USER }} >> prod.env
          echo REDIS_PASS=${{ secrets.REDIS_PASS }} >> prod.env

      - name: stop any existing containers
        run: docker compose -f docker-compose.prod.yml down

      - name: execute container
        run: docker compose -f docker-compose.prod.yml up -d