name: "Deploy Docker"

on: 
  workflow_call:
  workflow_dispatch:

env:
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  REDIS_USER: ${{ secrets.REDIS_USER }}
  REDIS_PASS: ${{ secrets.REDIS_PASS }}

jobs:
  run_container:
    runs-on: 
      labels: [ "self-hosted", "Linux" ]

    env:
      TAG: "ghcr.io/michiganlabs/hack-the-lab-backend:latest"
    
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Pull docker image
        run: docker pull $TAG

      - name: stop any existing containers
        run: docker compose -f docker-compose.prod.yml down

      - name: execute container
        run: docker compose -f docker-compose.prod.yml up -d