name: "Deploy Docker"

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  run_container:
    runs-on: 
      labels: [ "self-hosted", "Linux" ]

    env:
      TAG: "ghcr.io/michiganlabs/hack-the-lab-backend:latest"
    
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Pull docker image
        run: docker pull $TAG

      - name: Create environment file   
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          TEST_VARIABLE: ${{ vars.TEST_VARIABLE}}
        run: |
          echo "Nonsecret: $TEST_VARIABLE"
          echo "Nonsecret: ${{vars.TEST_VARIABLE}}"
          echo "Env: $POSTGRES_DB"
          echo "Secret: ${{ secrets.POSTGRES_DB }}"
          echo POSTGRES_DB=$POSTGRES_DB >> prod.env
          echo POSTGRES_USER=$POSTGRES_USER >> prod.env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> prod.env
          echo REDIS_USER=$REDIS_USER >> prod.env
          echo REDIS_PASS=$REDIS_PASS >> prod.env

      - name: Stop any existing containers
        run: docker compose -f docker-compose.prod.yml down

      - name: Start containers
        run: docker compose -f docker-compose.prod.yml up -d